### ISSUE TITLE
Breaks when used with `unified`

### ISSUE THREAD

**Issue by AlbinoGeek** [marko-knoebl/rehype-inline#3]
## Synopsis

I added `rehype-inline` to my otherwise working markdown+HTML pipeline, and it stopped working.

I added it after `rehypeRaw` so it gets a full tree, and before finalizing steps.

## Output

```
TypeError: Cannot read property 'unified' of undefined
```

### Stack Trace

```
uncaught
    at render (webpack-internal:///./lib/markdown.ts:37:65)
    at getStaticProps (webpack-internal:///./pages/[slug].tsx:48:79)
    at Object.renderToHTML (/home/damon/Projects/wikish/node_modules/next/dist/server/render.js:374:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async doRender (/home/damon/Projects/wikish/node_modules/next/dist/server/next-server.js:1127:38)
    at async /home/damon/Projects/wikish/node_modules/next/dist/server/next-server.js:1221:28
    at async /home/damon/Projects/wikish/node_modules/next/dist/server/response-cache.js:60:36
```

### TypeScript

```jsx
import rehypeInline from 'rehype-inline'

async function render(
  input: string
): Promise<string> {
  const result = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkEmoji, { emoticon: true })
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeRaw)
    .use(rehypeInline)
    .use(rehypeSlug)
    .use(rehypeToc, { nav: false })
    .use(rehypePresetMinify)
    .use(rehypeStringify, {
      quoteSmart:       true,
      closeSelfClosing: true,
      omitOptionalTags: true,
      entities:         { useShortestReferences: true }
    })
    .process(input)

  return result.toString()
}
```

### Markdown

```mdx
Hello World!
```

**Comment by ChristianMurphy** [comment]
@AlbinoGeek what version of unified are you using?
This plugin appears to use version 8
https://github.com/marko-knoebl/rehype-inline/blob/23ded437e925e1ce30b672ce2d615a9dc9a6c9fa/package.json#L17

version 9 and 10 are major versions (https://github.com/unifiedjs/unified/releases/tag/9.0.0 and https://github.com/unifiedjs/unified/releases/tag/10.0.0) which if not updated/test could cause breakage in this plugin.
It may be that this plugin needs to be updated to support version 9 and 10 @marko-knoebl

**Comment by AlbinoGeek** [comment]
```json
    "unified": "^10.1.0"
```

Gotcha, didn't realize this plugin was out-of-date*

I've moved to using `rehype-partials` and manual made my editor do the inlining.

**Comment by marko-knoebl** [comment]
Thanks for the report!

I've published a new version which is based on newer packages, including unified 10

So this should work with newer versions now.
